services:
  quackbus:
    image: elliotonthenet18/quackbus:latest
    container_name: quackbus
    ports:
      - "7277:7277"
    volumes:
      - ./downloads:/app/downloads
      - ./config:/app/config
      - ./logs:/app/logs  # Add logs volume
      - ./temp:/app/temp  
      - /path/to/your/music/folder:/app/music  # Change this to your actual music directory
    environment:
      # Download Configuration
      - DEFAULT_QUALITY=7  # 7=Hi-Res, 6=CD Quality, 5=MP3 320k
      - DOWNLOAD_PATH=/app/music
      - TEMP_PATH=/app/temp
      
      # Metadata Configuration
      - EMBED_ARTWORK=true
      - ORGANIZE_BY_ARTIST=true
      - CREATE_ALBUM_FOLDERS=true
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
